spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodapp_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: khoa1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
jwt:
  secret: mXG2DjwOfOOdU1t/0FUVvwUfmbafBDXQ1LrgBNVOw9o=
  expiration: 86400000
server:
  port: 8080
  servlet:
    context-path: /api/v1
logging:
  level:
    org.springframework.security: DEBUG
    com.foodapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
